config/routes.rb
Tweet360::Application.routes.draw do
  resources :users

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/blog', to: 'static_pages#blog'

  match '/status', to: 'static_pages#status'

  match '/terms', to: 'static_pages#terms'

  match '/privacy', to: 'static_pages#privacy'

  match '/advertisers', to: 'static_pages#advertisers'

  match '/business', to: 'static_pages#business'

  match '/developers', to: 'static_pages#developers'

  match '/resources', to: 'static_pages#resources'

  match '/media', to: 'static_pages#media'  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  include Gravtastic
  gravtastic secure: true

  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: { with: VALID_EMAIL_REGEX }, 
  					uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def blog
  end

  def status
  end

  def terms
  end

  def privacy
  end

  def advertisers
  end

  def business
  end

  def developers
  end

  def resources
  end

  def media
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		flash[:success] = "Welcome to the world of Tweet360!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Tweet360"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
	#def gravatar_for(user)
	#	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	#	gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png"
	#	image_tag(gravatar_url, alt: user.name, class: "gravatar")
	#end
	
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="https://github.com/Dev-Dipesh/tweet360">&copy; 2013 Tweet360</a>
	</small>

	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Blog", blog_path %></li>
			<li><%= link_to "Status", status_path %></li>
			<li><%= link_to "Terms", terms_path %></li>
			<li><%= link_to "Privacy", privacy_path %></li>
			<li><%= link_to "Advertisers", advertisers_path %></li>
			<li><%= link_to "Business", business_path %></li>
			<li><%= link_to "Media", media_path %></li>
			<li><%= link_to "Developers", developers_path %></li>
			<li><%= link_to "Resources", resources_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39757903-1', 'tweet360.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Tweet360", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home", root_path, id: "home" %></li>
						<li><%= link_to "Help", help_path, id: "help" %></li>
						<li><%= link_to "Sign in", '#', id: "signIn" %></li>
					</ul>
				</nav>
			</div>	
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<! [endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
	<%= render :partial => ‘layouts/ga’ if Rails.env.production? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	This is the about us page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/advertisers.html.erb
<% provide(:title, 'Advertisers') %>
<h1>Advertisers</h1>
<p>
	This is the advertisers page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<h1>Blog</h1>
<p>
	This is the blog page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/business.html.erb
<% provide(:title, 'Business') %>
<h1>Business</h1>
<p>
	This is the business page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/developers.html.erb
<% provide(:title, 'Developers') %>
<h1>Developers</h1>
<p>
	This is the developres page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	This is the help page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/home.html.erb
<%= link_to image_tag("tweet360 logo.png", align: "left", width: "400", height: "430", alt: "Tweet360 logo"), 'https://github.com/Dev-Dipesh/tweet360' %>
<div class="center hero-unit">
	<h1>Welcome to Tweet360</h1>
	
	<h2>
		Find out what's going on around you, right now, with the people and organizations you care the most.
	</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<script type="text/javascript">
$(function () {
	$("#slider1").slider({
		speed: 1000,
		width: 945,
		height: 350,
		autoPlay: true
	});
});
</script>

<link type="text/css" rel="stylesheet" href="jquery.slider.css" />
<script type="text/javascript" src="jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="jquery.easing.1.3.js"></script>
<script type="text/javascript" src="jquery.easing.compatibility.js"></script>
<script type="text/javascript" src="jquery.slider.min.js"></script>

<div id="slider1" class="slider">
	<div class="slider-box">
		<%= link_to image_tag("1.jpg", width: "945", height: "350", alt: "", class: "slider-item") %>
		<%= link_to image_tag("2.jpg", width: "945", height: "350", alt: "", class: "slider-item") %>
		<%= link_to image_tag("3.jpg", width: "945", height: "350", alt: "", class: "slider-item") %>
		<%= link_to image_tag("4.jpg", width: "945", height: "350", alt: "", class: "slider-item") %>
		<%= link_to image_tag("5.jpg", width: "945", height: "350", alt: "", class: "slider-item") %>

	</div>
	<div class="slider-control">
		<a href="#" class="slider-play"></a>
		<a href="#" class="slider-stop"></a>
	</div>		
	<div class="slider-nav">
		<a href="#"></a>
		<a href="#"></a>
		<a href="#"></a>
		<a href="#"></a>
		<a href="#"></a>
	</div>
	
</div>

app/views/static_pages/media.html.erb
<% provide(:title, 'Media') %>
<h1>Media</h1>
<p>
	This is the media page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/privacy.html.erb
<% provide(:title, 'Privacy') %>
<h1>Privacy</h1>
<p>
	This is the privacy policies page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/resources.html.erb
<% provide(:title, 'Resources') %>
<h1>Resources</h1>
<p>
	This is the resources page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/status.html.erb
<% provide(:title, 'Status') %>
<h1>Status</h1>
<p>
	This is the Tweet360's own status page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/static_pages/terms.html.erb
<% provide(:title, 'Terms') %>
<h1>Terms</h1>
<p>
	This is the terms and conditions (TOC) page for the
	<a href="https://github.com/Dev-Dipesh/tweet360">Tweet360</a> web application.
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= image_tag @user.gravatar_url %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>